### PR TITLE
Cosmetic fixes

### PR DESCRIPTION
**Pull request by cailadd90**
Further modifications to layout and text to improve usability.

### CODE REVIEW

**Comment by mcwimm** [comment]
@cailadd90 the file `MinibuoyIntro_3.md` is missing. Could you please upload the file?

**Comment by cailadd90** [comment]
> @cailadd90 the file `MinibuoyIntro_3.md` is missing. Could you please upload the file?

Strange, is it not in #42 in the man folder?

**Comment by cailadd90** [comment]
Oh I can see it's not there on GitHub... it says "everything's up to date" on my system - not sure why it didn't upload. I'll do it manually?

**Comment by cailadd90** [comment]
I answered my own question by just adding it manually - is that OK?

**Comment by mcwimm** [comment]
> I answered my own question by just adding it manually - is that OK?

That's perfect! Thanks.

**Comment by cailadd90** [comment]
Ooops! I think I know the problem - I removed the comparison of no. of inundation events from the summary table, but this has affected the text. I'll fix that now

**Comment by cailadd90** [comment]
> Ooops! I think I know the problem - I removed the comparison of no. of inundation events from the summary table, but this has affected the text. I'll fix that now

Ok in fun.hydrology.R, get.comparison.text() function, "Inundation proportion" needs to change to "Inundation duration" in 2 instances - then the bug is fixed. 

I tried pushing the change, but I've messed up my branches somehow.... I have a meeting I need to prepare for 11:00 (UK time) so need to work on that now. Feel free to make this change? I'll try fixing things on my end after 11:00.

**Comment by mcwimm** [comment]
> comparison

I replaced the strings but it's still not working for me. Will wait until you're done with your meeting...

**Comment by cailadd90** [comment]
> > comparison
> 
> I replaced the strings but it's still not working for me. Will wait until you're done with your meeting...

Pushed a commit, and it's working for me now. Want to check again? 
Screenshot 2023-08-25 at 11 15 17

**Comment by mcwimm** [comment]
Works!

**Pull request merged**
