### PR TITLE
Additional plots2

### PR DESCRIPTION
**Pull request by cailadd90**
Started again from AdditonalPlots branch, so that this branch now correctly displays the raw data and a stage velocity plot.

### CODE REVIEW

**Comment by mcwimm** [comment]
Nice! Imo, it's ready to be merged.

**Comment by mcwimm** [comment]
I'm wondering if showing the raw data again in comparison isn't a little too much:
image

**Comment by cailadd90** [comment]
agreed - happy to drop! Not needed really if this can be viewed in Target and Reference windows.

**Review by mcwimm — APPROVED** [review]
👍

**Pull request merged**
