### PR TITLE
Text for hydrodynamics comparison tab

### PR DESCRIPTION
**Pull request by cailadd90**
I have now added a dynamic text function to interpret the results of the associated table. It works on my own system, however I've been unable to produce the HTML text window in the App.

**server.R:**
I made two attemps at reading the comparison text, now hashed out.

**fun_ui_hydrology.R:**
Added a function to read the text as html. Not sure if this is correct.

**fun_graphics.R:**
Removed label = comma. This was a small feature used by the scales() package which we have now removed.

- [ ] @mcwimm: to integrate the text generation function into the App - thanks!

### CODE REVIEW

**Comment by mcwimm** [comment]
Displaying the text works but it looks a bit bulky:
image

Is this how it should look? It would be good if you could provide an example.
(I used the reference data sets but only the first few days.)

**Comment by cailadd90** [comment]
Ah glad you got it to work! I was concerned the text may be too long, plus I think I got the formatting wrong for adding returns / bullet points etc. I can now though run the App and tweak as needed. Happy also to share an example of what I intended it should look like on Word.

**Comment by mcwimm** [comment]
We can increase the width of the text box similar as is Target/Reference if this helps

**Comment by cailadd90** [comment]
For the default datasets, this is what I expect to find: 

ComparisonText

I wrote the code so it's meant to _not_ display "The target site benefits from" or "The target site is disadvantaged by" if there are no issues. So maybe I need to experiment with this a little more for various cases that it may not be working. 

The default messages in italics below are quite long, so I could shorten the first sentence and move the second one into the Mini Buoy Handbook?

If it's still too large, we could look to increase the width of the text output window.

**Comment by mcwimm** [comment]
Ok. This is a quite long. So I'd increase the width. Also not sure if you get the nice formatting that easy.

Didn't we want to use 'meaningfully different' instead of 'significantly'?

**Comment by cailadd90** [comment]
Cool. Let's try the width increase and see how it looks. We could also remove the bullets and headers, as this essentially repeats what's written in the table. I thought it helps though to spell out good/bad things about the target site. What do you think?

Good point - happy to use meaningfully different instead

**Pull request merged**
