### PR TITLE
New default datasets 

### PR DESCRIPTION
**Pull request by cailadd90**
for the B4+ design (so we can analyse wave orbital velocity) and the dataset is longer than 15 days.

### CODE REVIEW

**Comment by mcwimm** [comment]
Is there a reason that there is no inundation in the middle of the two data sets?
image

**Comment by cailadd90** [comment]
Yup – this will be neap tide when the location the mini buoy was deployed at was never inundated. An example of a window of opportunity.

C

From: mcwimm ***@***.***>
Reply to: Ale0430/MiniBuoy-App ***@***.***>
Date: Wednesday, 19 April 2023 at 09:34
To: Ale0430/MiniBuoy-App ***@***.***>
Cc: Cai Ladd ***@***.***>, Author ***@***.***>
Subject: Re: [Ale0430/MiniBuoy-App] New default datasets (PR #6)


Is there a reason that there is no inundation in the middle of the two data sets?
[Image removed by sender. image]<https://user-images.githubusercontent.com/48250781/233017436-5f1543ed-58ef-4a6b-a8e0-3c7986eb86ed.png>

**Comment by mcwimm** [comment]
> Yup – this will be neap tide when the location the mini buoy was deployed at was never inundated. An example of a window of opportunity.

Ah, cool. Then we can merge this PR 👍

**Comment by cailadd90** [comment]
Whoop!

From: mcwimm ***@***.***>
Reply to: Ale0430/MiniBuoy-App ***@***.***>
Date: Wednesday, 19 April 2023 at 09:39
To: Ale0430/MiniBuoy-App ***@***.***>
Cc: Cai Ladd ***@***.***>, Author ***@***.***>
Subject: Re: [Ale0430/MiniBuoy-App] New default datasets (PR #6)


Yup – this will be neap tide when the location the mini buoy was deployed at was never inundated. An example of a window of opportunity.

Ah, cool. Then we can merge this PR 👍

**Pull request merged**
