### PR TITLE
Revised output plots

### PR DESCRIPTION
**Pull request by cailadd90**
What's changed:
- modified the current and wave orbital velocity plots to display upper 90% percentile values, and no minimum value (since this is a little misleading due to detection limits)
- modified the ebb-flood comparison plot to now display hours to high tide, and changed the name from velocity stage plot

### CODE REVIEW

**Comment by mcwimm** [comment]
👍 works

Minor comments: 
- [ ] not showing a min in a pointrange might be a bit unconventional. Should we add a short descriptive sentence?
- [ ] the same adjustment should be applied to the comparison plot, shouldn't it?
image

**Comment by cailadd90** [comment]
Good points. I've just tried adding a caption in the labs argument:

+ labs(y            = 'Median wave orbital velocity (m/s)',
           caption  = 'Error bars represent upper 95th percentile and minimum detected value')

But alas ggplotly is not displaying the caption. Is there a way around this, in the same way you managed to present the legend? 

Maybe keeping the lower error bars in, with the description above, is better?

**Comment by mcwimm** [comment]
> * labs(y            = 'Median wave orbital velocity (m/s)',
>   caption  = 'Error bars represent upper 95th percentile and minimum detected value')

It will work with ggtitle:
```
labs(y = 'Median wave orbtial velocity (m/s)') + 
ggtitle('Error bars represent upper 95th percentile and minimum detected value') 
```

Shall we do it like that? Then I'll push the change. 

image

**Comment by cailadd90** [comment]
Yes that works, let's stick with the ggtitle for now.

**Comment by mcwimm** [comment]
> Yes that works, let's stick with the ggtitle for now.

Ok. Changed. Please checkout and try. Also applied the same change to comparison plots.

**Comment by cailadd90** [comment]
Looks great - thanks!

**Pull request merged**
