### PR TITLE
Quicker analysis

### PR DESCRIPTION
**Pull request by cailadd90**
Added a new argument to use a proportion of the data in detecting abrupt shifts. Testing showed using 25% of the data results in marked improvements in speed (i.e. chop = 0.25). Default is currently to use all the data (chop = 1), but maybe the default should be 25%.

- [ ] Cai - check how much the results change if 25% of the data is used for abrupt shift detection

### CODE REVIEW

**Comment by mcwimm** [comment]
Not working when chop = 0

**Comment by cailadd90** [comment]
> Not working when chop = 0

Sorry, I should have clarified. 'chop' represents the proportion of data to be used in searching for partially inundated cases. 1 = all the data, 0 = no data (so the analysis won't run with no data). Happy to use a better system, e.g. a binary choice: 'All' (chop = 1) or 'Reduced' (chop = 0.25)?

**Comment by mcwimm** [comment]
Ah, ok :) Now, it should work. Default is 50%, also throwing a "warning" to inform the user that not all data has been used. Please check wording of the warning :)

**Comment by cailadd90** [comment]
> Ah, ok :) Now, it should work. Default is 50%, also throwing a "warning" to inform the user that not all data has been used. Please check wording of the warning :)

Nice one!

**Comment by cailadd90** [comment]
It's working well, very happy to see how much the code speeds up. 

I would say the warning isn't required, as it's not that less data is being produced. It's simply that the precision of partially inundated cases may reduce, but testing has shown this to have a minimal effect (I will add this to the Mini Buoy handbook...). 

Some suggested changes to the custom settings titles:
- partial inundation window = search window
- minimum full inundation = minimum duration
- tilt full inundation = minimum tilt
- proportion data = search data

The message displayed when hovering over 'proportion data' could have another sentence added: "Using less data increases the speed of the analysis and has a minimal effect on the accuracy of detecting partially inundated cases."

**Comment by mcwimm** [comment]
Partial data search

**Pull request merged**
